version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: Australia/Melbourne
